name: galeriaflutter
description: A new Flutter project for Galeria de Pastores.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.2
  logger: ^2.4.0
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/PastorIcon.png"
  adaptative_icon_background: "#ffffff"
  adaptative_icon_foreground: "assets/images/PastorIconFor.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/